Test 19

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -54,7 +54,13 @@ jobs:
         run: |
             echo "Vulnerabilities found in the Safety scan:"
             jq '.' results.json
-            echo "Python vulnerability scan completed."
+            # Check the exit code of the safety command and handle failure
+             if [ $? -eq 64 ]; then
+                echo "Scan-failing vulnerabilities were found. Exiting with status 1."
+                exit 1
+             else
+                echo "Python vulnerability scan completed."
+             fi
         
     
     
